added deployment

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -330,6 +330,75 @@ jobs:
           echo "Trivy exit code: 0"
 
 
+       # ------------------------------------------------------
+      # 12. deploying to ec2
+      # ------------------------------------------------------   
+
+  deploy-to-ec2:
+      name: Deploy Application to EC2
+
+    # Deployment starts only after images are successfully
+    # built, scanned, and pushed to Docker Hub.
+      needs: docker-build-scan-and-push
+
+      runs-on: ubuntu-latest
+
+    # Deploy only for a push to main.
+    # Never deploy from a pull-request workflow.
+      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+
+      steps:
+      - name: Deploy latest images to EC2
+        uses: appleboy/ssh-action@v1.2.5
+        with:
+          # EC2 public IP or public DNS
+          host: ${{ secrets.EC2_HOST }}
+
+          # Ubuntu AMI's standard user
+          username: ${{ secrets.EC2_USERNAME }}
+
+          # Complete private key stored in GitHub Secrets
+          key: ${{ secrets.EC2_SSH_KEY }}
+
+          # Standard SSH port
+          port: 22
+
+          # Commands executed inside the EC2 machine
+          script: |
+            # Stop deployment immediately if a command fails.
+            set -e
+
+            echo "======================================"
+            echo "Starting Madhubani deployment"
+            echo "======================================"
+
+            # Enter the production deployment directory.
+            cd /home/ubuntu/madhubani-app
+
+            echo "Pulling the latest Docker images..."
+
+            # Pull only images whose registry versions changed.
+            docker compose pull
+
+            echo "Starting updated application..."
+
+            # Recreate changed containers and keep unchanged
+            # services running whenever possible.
+            docker compose up -d --remove-orphans
+
+            echo "Removing unused Docker images..."
+
+            # Prevent old image layers from consuming EC2 disk space.
+            docker image prune -f
+
+            echo "Current container status:"
+            docker compose ps
+
+            echo "======================================"
+            echo "Deployment completed successfully"
+            echo "======================================"
+
+
 
 
 
